@baseURL = http://localhost:3000
@bearerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGlmcnMuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU5MzYxNzY5LCJleHAiOjE3NTkzNjUzNjl9.ZoRCA0J_UwboAghzBzVoj8k3OfFHOcIw3tw3SmGZtgQ

### Listar todos os eventos
GET {{baseURL}}/eventos/consultar
Authorization: Bearer {{bearerToken}}

### Listar todos os usuarios
GET {{baseURL}}/voluntarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGlmcnMuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU5MzYxNzY5LCJleHAiOjE3NTkzNjUzNjl9.ZoRCA0J_UwboAghzBzVoj8k3OfFHOcIw3tw3SmGZtgQ

### Criar um novo evento
POST {{baseURL}}/eventos/registrar
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
 "titulo": "Musical Rock",
 "data_evento": "2025-10-15"
}

### Criar um novo usuário
POST {{baseURL}}/users/register
Content-Type: application/json

{
 "nome": "bernardo",
 "telefone": "549999999999",
 "email": "bernardo2@ifrs.com",
 "senha": "123"
}

### Logar usuário
POST {{baseURL}}/users/auth
Content-Type: application/json

{
 "email": "admin@ifrs.com",
 "senha": "123"
}
